### PR TITLE
Added VertexFormula in C#

### PR DESCRIPTION
**Pull request by MajorGrits**
Added the vertex formula in the C# language.

### CODE REVIEW

**Comment by MajorGrits** [comment]
Yeah good idea. Completely misunderstood the formula.

**Comment by BaReinhard** [comment]
Either have it return a Tuple or if its prior to the .NET 4.0 use KeyValuePair, it's also possible to have the function use an out parameter, but that seems pretty clunky to me, but then again I'm not really a c# dev.

**Comment by MajorGrits** [comment]
Want me to do another PR for the changes or can I tack it onto this one? Unfamiliar with how that works.

**Comment by BaReinhard** [comment]
Yeah make the change then make another pr, sorry I forgot about the div 0 issue.

**Pull request merged**
